# Generated by Django 5.1.3 on 2024-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
